### ISSUE TITLE
Command used to point to the Xinerama dependency

### ISSUE THREAD

**Issue by theuring** [asafge/xrdp_dualmon#1]
Hello Asaf,

First of all thank you for this contribution! 
We are trying out your short "how to" and are stuck on the step:
- Compile and install xrdp with the xinerama dependency.

Could you share your command you used to do this?

Best regards,

Thomas

**Comment by speidy** [comment]
Hi,
1. you need to install libXinerama development package 'yum install libXinerama-devel'
2. walk through xrdp installation guide in www.xrdp.org (Doc: http://www.xrdp.org/index.php?option=com_content&view=article&id=16:building-on-debian-6&catid=2:documents&Itemid=7)

To build it
